apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-ci-cd
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-ci-cd
  template:
    metadata:
      labels:
        app: demo-ci-cd
    spec:
      containers:
      - name: web
        image: phumthanarat/demo-ci-cd:v1.0.0
        ports:
        - containerPort: 80

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10