apiVersion: v1
kind: Service
metadata:
  name: demo-ci-cd-service
  namespace: jenkins
spec:
  selector:
    app: demo-ci-cd
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
